---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: crd-role-controller
spec:
  resources:
   - apiVersion: apiextensions.k8s.io/v1
     resource: customresourcedefinitions
     annotationSelector:
       matchExpressions:
        - {key: enable-default-roles, operator: Exists}
  attachments:
  - apiVersion: rbac.authorization.k8s.io/v1
    resource: clusterroles
  hooks:
    sync:
      webhook:
        url: http://crd-role-controller.metacontroller/sync-crd-role
        timeout: 10s