apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name:  my-tests.ctl.rlg.io
  annotations:
    enable-default-roles: "yes"
spec:
  group: ctl.rlg.io
  scope: Cluster
  names:
    plural: my-tests
    singular: my-test
    kind: MyTest
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
