apiVersion: ctl.enisoc.com/v1
kind: IndexedJob
metadata:
  name: print-index
spec:
  completions: 10
  parallelism: 2
  template:
    metadata:
      labels:
        app: print-index
    spec:
      restartPolicy: OnFailure
      containers:
      - name: print-index
        image: busybox
        command: ["sh", "-c", "echo ${JOB_INDEX}"]
