---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: globalconfigmaps.examples.metacontroller.io
spec:
  group: examples.metacontroller.io
  scope: Cluster
  names:
    plural: globalconfigmaps
    singular: globalconfigmap
    kind: GlobalConfigMap
    shortNames: ["gcm"]
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              sourceName:
                description: 'Name of configmap to propagate'
                type: string
              sourceNamespace:
                description: 'Namespace in which configmap to propagate is located'
                type: string
            required:
            - sourceName
            - sourceNamespace
        required:
        - spec
    subresources:
      status: {}