version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gosec
    - importas
    - misspell
    - nilerr
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gosec:
      excludes:
        - G108
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/client/generated
      - examples
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg/client/generated
      - examples
      - third_party$
      - builtin$
      - examples$
