# This is the same as Dockerfile, but skips `dep ensure`.
# It assumes you already ran that locally.
FROM golang:1.10 AS build

COPY . /go/src/k8s.io/metacontroller/
WORKDIR /go/src/k8s.io/metacontroller/
RUN go install

FROM debian:stretch-slim
COPY --from=build /go/bin/metacontroller /usr/bin/
RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates && rm -rf /var/lib/apt/lists/*
CMD ["/usr/bin/metacontroller"]
