FROM golang:1.16.3 AS build

ARG TAG
ENV TAG=${TAG:-dev}

COPY . /go/src/metacontroller.io/
WORKDIR /go/src/metacontroller.io/
ENV CGO_ENABLED=0
RUN make install

FROM gcr.io/distroless/base-debian10:debug-nonroot
USER nonroot:nonroot
COPY --from=build /go/bin/metacontroller.io /usr/bin/metacontroller
CMD ["/usr/bin/metacontroller"]
