FROM golang:1.10 AS build

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

COPY . /go/src/metacontroller.app/
WORKDIR /go/src/metacontroller.app/
RUN hack/get-kube-binaries.sh
RUN dep ensure
RUN go install
RUN make unit-test
RUN make integration-test
