FROM golang:1.15.6 AS build

COPY . /go/src/metacontroller.io/
WORKDIR /go/src/metacontroller.io/
ENV CGO_ENABLED=0
RUN make vendor && go install

FROM gcr.io/distroless/base-debian10:nonroot
USER nonroot:nonroot
COPY --from=build /go/bin/metacontroller.io /usr/bin/metacontroller
CMD ["/usr/bin/metacontroller"]
