
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Adding the generators here allows us to pin them to a particular version.
required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen"
  ]

# The code in examples/ is not part of the actual build.
ignored = [
  "metacontroller.app/examples/*"
]

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5" # same minor version track as used by apimachinery@kubernetes-1.11.0

[[override]]
  name = "github.com/prometheus/client_model"
  revision = "99fa1f4be8e564e8a6b613da7fa6f46c9edafc6c"
# last version compatable with golang/protobuf@v1.0.0 (the version used by apimachinery@kubernetes-1.9.9)

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
