# Override volumemounts for listoptions mode.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metacontroller
  namespace: metacontroller
spec:
  template:
    spec:
      containers:
        - name: metacontroller
          volumeMounts:
            - mountPath: /etc/metacontroller/list-options-config
              name: metacontroller-configmap
