---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: crd-role-controller
spec:
  resources:
  - apiVersion: apiextensions.k8s.io/v1beta1
    resource: customresourcedefinitions
    annotationSelector:
      matchExpressions:
      - {key: enable-default-roles, operator: Exists}
  attachments:
  - apiVersion: rbac.authorization.k8s.io/v1
    resource: clusterroles
  hooks:
    sync:
      webhook:
        url: http://crd-role-controller.metacontroller/sync-crd-role
        timeout: 10s
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: crd-role-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crd-role-controller
  template:
    metadata:
      labels:
        app: crd-role-controller
    spec:
      containers:
      - name: controller
        image: python:2.7
        command: ["python", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: crd-role-controller
---
apiVersion: v1
kind: Service
metadata:
  name: crd-role-controller
  namespace: metacontroller
spec:
  selector:
    app: crd-role-controller
  ports:
  - port: 80
