---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: daemonjobs.ctl.example.com
spec:
  group: ctl.example.com
  scope: Namespaced
  names:
    plural: daemonjobs
    singular: daemonjob
    kind: DaemonJob
    shortNames: ["dj"]
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}