apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metacontroller
  namespace: metacontroller
spec:
  template:
    spec:
      containers:
      - name: metacontroller
        ports:
          - containerPort: 9999
            name: "metrics"
            protocol: "TCP"
