apiVersion: v1
kind: Service
metadata:
  name: metacontroller
  namespace: metacontroller
  labels:
    app.kubernetes.io/name: metacontroller
spec:
  ports:
    - port: 9999
      name: metrics
      targetPort: 9999
      protocol: TCP
  selector:
    app.kubernetes.io/name: metacontroller