apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmaplists.examples.metacontroller.io
spec:
  group: examples.metacontroller.io
  names:
    kind: ConfigMapList
    listKind: ConfigMapListList
    plural: configmaplists
    singular: configmaplist
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              sourceNamespace:
                type: string
              sourceLabels:
                type: object
                additionalProperties:
                  type: string
            required:
            - sourceNamespace
            - sourceLabels
          status:
            type: object
            properties:
              count:
                type: integer
              observedGeneration:
                type: integer
        required:
        - spec
    served: true
    storage: true
    subresources:
      status: {}
