---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmappropagations.examples.metacontroller.io
spec:
  group: examples.metacontroller.io
  scope: Cluster
  names:
    plural: configmappropagations
    singular: configmappropagation
    kind: ConfigMapPropagation
    shortNames: ["cp"]
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              sourceName:
                description: 'Name of configmap to propagate'
                type: string
              sourceNamespace:
                description: 'Namespace in which configmap to propagate is located'
                type: string
              targetNamespaces:
                type: array
                items:
                  type: string
            required:
            - sourceName
            - sourceNamespace
            - targetNamespaces
        required:
        - spec
    subresources:
      status: {}
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: configmap-propagation-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: examples.metacontroller.io/v1alpha1
    resource: configmappropagations
  childResources:
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://configmap-propagation-controller.metacontroller/sync
    customize:
      webhook:
        url: http://configmap-propagation-controller.metacontroller/customize
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-propagation-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-propagation-controller
  template:
    metadata:
      labels:
        app: configmap-propagation-controller
    spec:
      containers:
      - name: controller
        image: python:3.9
        command: ["python", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: configmap-propagation-controller
---
apiVersion: v1
kind: Service
metadata:
  name: configmap-propagation-controller
  namespace: metacontroller
spec:
  selector:
    app: configmap-propagation-controller
  ports:
  - port: 80