---
apiVersion: v1
kind: Namespace
metadata:
  name: secure-omega
---
apiVersion: v1
kind: Namespace
metadata:
  name: secure-alpha
  labels:
    propagate-secure: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: secure-beta
  labels:
    propagate-secure: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: secure-gamma
