---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: noops.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: noops
    singular: noop
    kind: Noop
  subresources:
    status: {}