apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: catsets.ctl.enisoc.com
spec:
  group: ctl.enisoc.com
  version: v1
  scope: Namespaced
  names:
    plural: catsets
    singular: catset
    kind: CatSet
    shortNames:
    - cs
  subresources:
    status: {}
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: catset-controller
spec:
  parentResource:
    apiVersion: ctl.enisoc.com/v1
    resource: catsets
    revisionHistory:
      fieldPaths:
      - spec.template
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: RollingRecreate
      statusChecks:
        conditions:
        - type: Ready
          status: "True"
  - apiVersion: v1
    resource: persistentvolumeclaims
  hooks:
    sync:
      webhook:
        url: http://catset-controller.metacontroller/sync
    finalize:
      webhook:
        url: http://catset-controller.metacontroller/sync
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: catset-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catset-controller
  template:
    metadata:
      labels:
        app: catset-controller
    spec:
      containers:
      - name: controller
        image: metacontroller/nodejs-server:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: hooks
          mountPath: /node/hooks
      volumes:
      - name: hooks
        configMap:
          name: catset-controller
---
apiVersion: v1
kind: Service
metadata:
  name: catset-controller
  namespace: metacontroller
spec:
  selector:
    app: catset-controller
  ports:
  - port: 80
