{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "metacontroller.fullname" . }}
  labels:
    {{- include "metacontroller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
{{- end}}
