{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "metacontroller.fullname" . }}
  labels:
    {{- include "metacontroller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metacontroller.serviceAccountName" . }}
    namespace: {{ include "metacontroller.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "metacontroller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
