{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "metacontroller.fullname" . }}
  labels:
    {{- include "metacontroller.labels" . | nindent 4 }}
aggregationRule:
  {{- toYaml .Values.clusterRole.aggregationRule | nindent 2 }}
rules:
  {{- toYaml .Values.clusterRole.rules | nindent 2 }}
{{- end}}
