{{- if and .Values.podDisruptionBudget (gt (.Values.replicas | int) 1) }}
apiVersion: {{ ternary "policy/v1" "policy/v1beta1" (semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version) }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "metacontroller.fullname" . }}
  labels:
    {{- include "metacontroller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "metacontroller.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end -}}
