{{- if and .Values.service .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metacontroller.fullname" . }}
  namespace: {{ include "metacontroller.namespace" . }}
  labels:
    {{- include "metacontroller.labels" . | nindent 4 }}
spec:
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "metacontroller.name" . }}
{{- end }}
