# Override args for development mode.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metacontroller
  namespace: metacontroller
spec:
  template:
    spec:
      containers:
      - name: metacontroller
        args:
        - --logtostderr
        - -v=5
        - --discovery-interval=5s
        - --client-go-qps=100
        - --client-go-burst=200
