apiVersion: v1
kind: ServiceAccount
metadata:
  name: metacontroller
  namespace: metacontroller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metacontroller
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metacontroller
subjects:
  - kind: ServiceAccount
    name: metacontroller
    namespace: metacontroller
roleRef:
  kind: ClusterRole
  name: metacontroller
  apiGroup: rbac.authorization.k8s.io
