---
apiVersion: v1
kind: Namespace
metadata:
  name: omega
---
apiVersion: v1
kind: Secret
metadata:
  name: shareable
  namespace: omega
data:
  some: dmFsdWUK
  other: dmFsdWUK
---
apiVersion: v1
kind: Namespace
metadata:
  name: alpha
  labels:
    propagate: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: beta
  labels:
    propagate: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gamma
---
apiVersion: examples.metacontroller.io/v1alpha1
kind: SecretPropagation
metadata:
  name: secret-propagation
spec:
  sourceName: shareable
  sourceNamespace: omega
  targetNamespaceLabelSelector:
    matchLabels:
      propagate: "true"

