apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: catsets.ctl.enisoc.com
spec:
  group: ctl.enisoc.com
  version: v1
  scope: Namespaced
  names:
    plural: catsets
    singular: catset
    kind: CatSet
    shortNames:
    - cs
  subresources:
    status: {}