apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: things.ctl.enisoc.com
spec:
  group: ctl.enisoc.com
  version: v1
  scope: Namespaced
  names:
    plural: things
    singular: thing
    kind: Thing
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: thing-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: ctl.enisoc.com/v1
    resource: things
  childResources:
    - apiVersion: v1
      resource: pods
  hooks:
    sync:
      webhook:
        url: http://thing-controller.metacontroller/sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thing-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thing-controller
  template:
    metadata:
      labels:
        app: thing-controller
    spec:
      containers:
      - name: controller
        image: enisoc/thing-controller:latest
        command: ["thing-controller"]
---
apiVersion: v1
kind: Service
metadata:
  name: thing-controller
  namespace: metacontroller
spec:
  selector:
    app: thing-controller
  ports:
  - port: 80
    targetPort: 8080
