---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreen-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen-controller
  template:
    metadata:
      labels:
        app: bluegreen-controller
    spec:
      containers:
      - name: controller
        image: metacontroller/nodejs-server:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: hooks
          mountPath: /node/hooks
      volumes:
      - name: hooks
        configMap:
          name: bluegreen-controller
---
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-controller
  namespace: metacontroller
spec:
  selector:
    app: bluegreen-controller
  ports:
  - port: 80
