---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: globalconfigmap-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: examples.metacontroller.io/v1alpha1
    resource: globalconfigmaps
  childResources:
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://globalconfigmap-controller.metacontroller/sync
    customize:
      webhook:
        url: http://globalconfigmap-controller.metacontroller/customize
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: globalconfigmap-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globalconfigmap-controller
  template:
    metadata:
      labels:
        app: globalconfigmap-controller
    spec:
      containers:
      - name: controller
        image: python:3.9
        command: ["python", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: globalconfigmap-controller
---
apiVersion: v1
kind: Service
metadata:
  name: globalconfigmap-controller
  namespace: metacontroller
spec:
  selector:
    app: globalconfigmap-controller
  ports:
  - port: 80