---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: daemonjobs.ctl.example.com
spec:
  group: ctl.example.com
  version: v1
  scope: Namespaced
  names:
    plural: daemonjobs
    singular: daemonjob
    kind: DaemonJob
    shortNames: ["dj"]
  subresources:
    status: {}
