apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bluegreendeployments.ctl.enisoc.com
spec:
  group: ctl.enisoc.com
  version: v1
  scope: Namespaced
  names:
    plural: bluegreendeployments
    singular: bluegreendeployment
    kind: BlueGreenDeployment
    shortNames:
    - bgd
  subresources:
    status: {}
