// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationSelector) DeepCopyInto(out *AnnotationSelector) {
	*out = *in
	if in.MatchAnnotations != nil {
		in, out := &in.MatchAnnotations, &out.MatchAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationSelector.
func (in *AnnotationSelector) DeepCopy() *AnnotationSelector {
	if in == nil {
		return nil
	}
	out := new(AnnotationSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildUpdateStatusChecks) DeepCopyInto(out *ChildUpdateStatusChecks) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]StatusConditionCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildUpdateStatusChecks.
func (in *ChildUpdateStatusChecks) DeepCopy() *ChildUpdateStatusChecks {
	if in == nil {
		return nil
	}
	out := new(ChildUpdateStatusChecks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientConfig) DeepCopyInto(out *ClientConfig) {
	*out = *in
	out.Service = in.Service
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientConfig.
func (in *ClientConfig) DeepCopy() *ClientConfig {
	if in == nil {
		return nil
	}
	out := new(ClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeController) DeepCopyInto(out *CompositeController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeController.
func (in *CompositeController) DeepCopy() *CompositeController {
	if in == nil {
		return nil
	}
	out := new(CompositeController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompositeController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerChildResourceRule) DeepCopyInto(out *CompositeControllerChildResourceRule) {
	*out = *in
	out.ResourceRule = in.ResourceRule
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		if *in == nil {
			*out = nil
		} else {
			*out = new(CompositeControllerChildUpdateStrategy)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerChildResourceRule.
func (in *CompositeControllerChildResourceRule) DeepCopy() *CompositeControllerChildResourceRule {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerChildResourceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerChildUpdateStrategy) DeepCopyInto(out *CompositeControllerChildUpdateStrategy) {
	*out = *in
	in.StatusChecks.DeepCopyInto(&out.StatusChecks)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerChildUpdateStrategy.
func (in *CompositeControllerChildUpdateStrategy) DeepCopy() *CompositeControllerChildUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerChildUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerHooks) DeepCopyInto(out *CompositeControllerHooks) {
	*out = *in
	if in.Sync != nil {
		in, out := &in.Sync, &out.Sync
		if *in == nil {
			*out = nil
		} else {
			*out = new(CompositeControllerSyncHook)
			**out = **in
		}
	}
	if in.PreUpdateChild != nil {
		in, out := &in.PreUpdateChild, &out.PreUpdateChild
		if *in == nil {
			*out = nil
		} else {
			*out = new(CompositeControllerPreUpdateChildHook)
			**out = **in
		}
	}
	if in.PostUpdateChild != nil {
		in, out := &in.PostUpdateChild, &out.PostUpdateChild
		if *in == nil {
			*out = nil
		} else {
			*out = new(CompositeControllerPostUpdateChildHook)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerHooks.
func (in *CompositeControllerHooks) DeepCopy() *CompositeControllerHooks {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerHooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerList) DeepCopyInto(out *CompositeControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CompositeController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerList.
func (in *CompositeControllerList) DeepCopy() *CompositeControllerList {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompositeControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerParentResourceRule) DeepCopyInto(out *CompositeControllerParentResourceRule) {
	*out = *in
	out.ResourceRule = in.ResourceRule
	if in.RevisionHistory != nil {
		in, out := &in.RevisionHistory, &out.RevisionHistory
		if *in == nil {
			*out = nil
		} else {
			*out = new(CompositeControllerRevisionHistory)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerParentResourceRule.
func (in *CompositeControllerParentResourceRule) DeepCopy() *CompositeControllerParentResourceRule {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerParentResourceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerPostUpdateChildHook) DeepCopyInto(out *CompositeControllerPostUpdateChildHook) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerPostUpdateChildHook.
func (in *CompositeControllerPostUpdateChildHook) DeepCopy() *CompositeControllerPostUpdateChildHook {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerPostUpdateChildHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerPreUpdateChildHook) DeepCopyInto(out *CompositeControllerPreUpdateChildHook) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerPreUpdateChildHook.
func (in *CompositeControllerPreUpdateChildHook) DeepCopy() *CompositeControllerPreUpdateChildHook {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerPreUpdateChildHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerRevisionHistory) DeepCopyInto(out *CompositeControllerRevisionHistory) {
	*out = *in
	if in.FieldPaths != nil {
		in, out := &in.FieldPaths, &out.FieldPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerRevisionHistory.
func (in *CompositeControllerRevisionHistory) DeepCopy() *CompositeControllerRevisionHistory {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerRevisionHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerSpec) DeepCopyInto(out *CompositeControllerSpec) {
	*out = *in
	in.ParentResource.DeepCopyInto(&out.ParentResource)
	if in.ChildResources != nil {
		in, out := &in.ChildResources, &out.ChildResources
		*out = make([]CompositeControllerChildResourceRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ClientConfig = in.ClientConfig
	in.Hooks.DeepCopyInto(&out.Hooks)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerSpec.
func (in *CompositeControllerSpec) DeepCopy() *CompositeControllerSpec {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerStatus) DeepCopyInto(out *CompositeControllerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerStatus.
func (in *CompositeControllerStatus) DeepCopy() *CompositeControllerStatus {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeControllerSyncHook) DeepCopyInto(out *CompositeControllerSyncHook) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeControllerSyncHook.
func (in *CompositeControllerSyncHook) DeepCopy() *CompositeControllerSyncHook {
	if in == nil {
		return nil
	}
	out := new(CompositeControllerSyncHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerRevision) DeepCopyInto(out *ControllerRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.ParentPatch.DeepCopyInto(&out.ParentPatch)
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]ControllerRevisionChildren, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerRevision.
func (in *ControllerRevision) DeepCopy() *ControllerRevision {
	if in == nil {
		return nil
	}
	out := new(ControllerRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerRevisionChildren) DeepCopyInto(out *ControllerRevisionChildren) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerRevisionChildren.
func (in *ControllerRevisionChildren) DeepCopy() *ControllerRevisionChildren {
	if in == nil {
		return nil
	}
	out := new(ControllerRevisionChildren)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerRevisionList) DeepCopyInto(out *ControllerRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerRevisionList.
func (in *ControllerRevisionList) DeepCopy() *ControllerRevisionList {
	if in == nil {
		return nil
	}
	out := new(ControllerRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorController) DeepCopyInto(out *DecoratorController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorController.
func (in *DecoratorController) DeepCopy() *DecoratorController {
	if in == nil {
		return nil
	}
	out := new(DecoratorController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DecoratorController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorControllerAttachmentRule) DeepCopyInto(out *DecoratorControllerAttachmentRule) {
	*out = *in
	out.ResourceRule = in.ResourceRule
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		if *in == nil {
			*out = nil
		} else {
			*out = new(DecoratorControllerAttachmentUpdateStrategy)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorControllerAttachmentRule.
func (in *DecoratorControllerAttachmentRule) DeepCopy() *DecoratorControllerAttachmentRule {
	if in == nil {
		return nil
	}
	out := new(DecoratorControllerAttachmentRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorControllerAttachmentUpdateStrategy) DeepCopyInto(out *DecoratorControllerAttachmentUpdateStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorControllerAttachmentUpdateStrategy.
func (in *DecoratorControllerAttachmentUpdateStrategy) DeepCopy() *DecoratorControllerAttachmentUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(DecoratorControllerAttachmentUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorControllerHooks) DeepCopyInto(out *DecoratorControllerHooks) {
	*out = *in
	if in.Sync != nil {
		in, out := &in.Sync, &out.Sync
		if *in == nil {
			*out = nil
		} else {
			*out = new(DecoratorControllerSyncHook)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorControllerHooks.
func (in *DecoratorControllerHooks) DeepCopy() *DecoratorControllerHooks {
	if in == nil {
		return nil
	}
	out := new(DecoratorControllerHooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorControllerList) DeepCopyInto(out *DecoratorControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DecoratorController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorControllerList.
func (in *DecoratorControllerList) DeepCopy() *DecoratorControllerList {
	if in == nil {
		return nil
	}
	out := new(DecoratorControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DecoratorControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorControllerResourceRule) DeepCopyInto(out *DecoratorControllerResourceRule) {
	*out = *in
	out.ResourceRule = in.ResourceRule
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.LabelSelector)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.AnnotationSelector != nil {
		in, out := &in.AnnotationSelector, &out.AnnotationSelector
		if *in == nil {
			*out = nil
		} else {
			*out = new(AnnotationSelector)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorControllerResourceRule.
func (in *DecoratorControllerResourceRule) DeepCopy() *DecoratorControllerResourceRule {
	if in == nil {
		return nil
	}
	out := new(DecoratorControllerResourceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorControllerSpec) DeepCopyInto(out *DecoratorControllerSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]DecoratorControllerResourceRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]DecoratorControllerAttachmentRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ClientConfig = in.ClientConfig
	in.Hooks.DeepCopyInto(&out.Hooks)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorControllerSpec.
func (in *DecoratorControllerSpec) DeepCopy() *DecoratorControllerSpec {
	if in == nil {
		return nil
	}
	out := new(DecoratorControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorControllerStatus) DeepCopyInto(out *DecoratorControllerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorControllerStatus.
func (in *DecoratorControllerStatus) DeepCopy() *DecoratorControllerStatus {
	if in == nil {
		return nil
	}
	out := new(DecoratorControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecoratorControllerSyncHook) DeepCopyInto(out *DecoratorControllerSyncHook) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecoratorControllerSyncHook.
func (in *DecoratorControllerSyncHook) DeepCopy() *DecoratorControllerSyncHook {
	if in == nil {
		return nil
	}
	out := new(DecoratorControllerSyncHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRule) DeepCopyInto(out *ResourceRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRule.
func (in *ResourceRule) DeepCopy() *ResourceRule {
	if in == nil {
		return nil
	}
	out := new(ResourceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceReference) DeepCopyInto(out *ServiceReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceReference.
func (in *ServiceReference) DeepCopy() *ServiceReference {
	if in == nil {
		return nil
	}
	out := new(ServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusConditionCheck) DeepCopyInto(out *StatusConditionCheck) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusConditionCheck.
func (in *StatusConditionCheck) DeepCopy() *StatusConditionCheck {
	if in == nil {
		return nil
	}
	out := new(StatusConditionCheck)
	in.DeepCopyInto(out)
	return out
}
