---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "api-approved.kubernetes.io": "unapproved, request not yet submitted"
  name: noops.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  scope: Namespaced
  names:
    plural: noops
    singular: noop
    kind: Noop
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}