name: Lint Charts

on: [ pull_request ]

jobs:
  lint-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs deploy/helm --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: |
          ct lint --chart-dirs deploy/helm \
          --chart-yaml-schema '.github/actions/chart-testing/etc/chart_schema.yaml' \
          --lint-conf '.github/actions/chart-testing/etc/lintconf.yaml' \
          --validate-maintainers=false \
          --check-version-increment=false \
          --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: |
          ct install --chart-dirs deploy/helm \
          --target-branch ${{ github.event.repository.default_branch }}
